# Generated by Django 6.0.3 on 2026-04-18 07:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, help_text='Voter Identification Number (assigned after approval)', max_length=20, null=True, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('lga_of_origin', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('polling_unit', models.CharField(max_length=100)),
                ('residence_state', models.CharField(max_length=50)),
                ('residence_lga', models.CharField(max_length=100)),
                ('residence_address', models.TextField()),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='draft', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, choices=[('underage', 'Underage (below 18 years)'), ('document_mismatch', 'Document information mismatch'), ('biometric_failure', 'Biometric verification failed'), ('duplicate', 'Duplicate registration detected'), ('anomaly_detected', 'Anomaly detected in registration'), ('manual_review', 'Requires manual review')], max_length=50)),
                ('rejection_details', models.TextField(blank=True)),
                ('ai_verification_score', models.FloatField(default=0.0, help_text='Overall AI verification confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('age_verification_passed', models.BooleanField(default=False)),
                ('document_verification_passed', models.BooleanField(default=False)),
                ('biometric_verification_passed', models.BooleanField(default=False)),
                ('anomaly_detection_passed', models.BooleanField(default=False)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('registration_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voter Registration',
                'verbose_name_plural': 'Voter Registrations',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryVoterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('card_data', models.JSONField(default=dict, help_text='JSON data for card generation')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='temp_cards/')),
                ('is_active', models.BooleanField(default=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_card', to='registration.voterregistration')),
            ],
            options={
                'verbose_name': 'Temporary Voter Card',
                'verbose_name_plural': 'Temporary Voter Cards',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('personal_info', 'Personal Information'), ('residence', 'Residence & LGA Selection'), ('documents', 'Document Upload & OCR'), ('biometrics', 'Biometric Capture'), ('verification', 'AI Verification & Review'), ('complete', 'Registration Complete')], default='personal_info', max_length=20)),
                ('step_data', models.JSONField(default=dict, help_text='JSON data for the current step')),
                ('completed_steps', models.JSONField(default=list, help_text='List of completed step identifiers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_step', to='registration.voterregistration')),
            ],
            options={
                'verbose_name': 'Registration Step',
                'verbose_name_plural': 'Registration Steps',
            },
        ),
        migrations.AddIndex(
            model_name='voterregistration',
            index=models.Index(fields=['vin'], name='registratio_vin_8c0410_idx'),
        ),
        migrations.AddIndex(
            model_name='voterregistration',
            index=models.Index(fields=['status', 'registration_date'], name='registratio_status_f2e9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='voterregistration',
            index=models.Index(fields=['state_of_origin', 'lga_of_origin'], name='registratio_state_o_e9baab_idx'),
        ),
        migrations.AddIndex(
            model_name='voterregistration',
            index=models.Index(fields=['ai_verification_score'], name='registratio_ai_veri_b89d98_idx'),
        ),
    ]
