# Generated by Django 6.0.3 on 2026-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_voterregistration_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregistration',
            name='ai_verification_layers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='ai_verification_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='facial_image',
            field=models.ImageField(blank=True, null=True, upload_to='biometrics/faces/'),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='facial_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='facial_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='fingerprint_image',
            field=models.ImageField(blank=True, null=True, upload_to='biometrics/fingerprints/'),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='fingerprint_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='fingerprint_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='is_underage_suspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_address_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_address_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/address/'),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_address_ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_age_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_age_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/age/'),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_age_ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_identity_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_identity_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/identity/'),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='proof_of_identity_ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='step_1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='step_2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='step_3_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='step_4_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='temporary_voter_card',
            field=models.FileField(blank=True, null=True, upload_to='tvc/'),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='verification_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
