# Generated by Django 6.0.3 on 2026-04-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_voterregistration_ai_verification_layers_and_more'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voterregistration',
            new_name='registratio_state_o_40d8f3_idx',
            old_name='registratio_state_o_e9baab_idx',
        ),
        migrations.RemoveField(
            model_name='registrationstep',
            name='current_step',
        ),
        migrations.AddField(
            model_name='registrationstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationstep',
            name='step_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registrationstep',
            name='step_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='registration.voterregistration'),
        ),
        migrations.AlterField(
            model_name='voterregistration',
            name='lga_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters_origin', to='utils.localgovernmentarea'),
        ),
        migrations.AlterField(
            model_name='voterregistration',
            name='residence_lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters_residence', to='utils.localgovernmentarea'),
        ),
        migrations.AlterField(
            model_name='voterregistration',
            name='residence_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters_residence', to='utils.nigerianstate'),
        ),
        migrations.AlterField(
            model_name='voterregistration',
            name='state_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters_origin', to='utils.nigerianstate'),
        ),
    ]
