# Generated by Django 4.2.7 on 2026-04-29 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_rename_registratio_state_o_e9baab_idx_registratio_state_o_40d8f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('national_id', 'National ID (NIMC)'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('baptismal_certificate', 'Baptismal Certificate')], max_length=30)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('ocr_text', models.TextField(blank=True, help_text='Extracted text from OCR processing')),
                ('extracted_data', models.JSONField(default=dict, help_text='Structured data extracted from document')),
                ('confidence_score', models.FloatField(default=0.0, help_text='OCR confidence score (0-1)')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration.voterregistration')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authentic', models.BooleanField(default=False, help_text='Whether document appears authentic')),
                ('authenticity_score', models.FloatField(default=0.0, help_text='Authenticity confidence score (0-1)')),
                ('verification_details', models.JSONField(default=dict, help_text='Detailed verification results')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='documents.document')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['registration', 'document_type'], name='documents_d_registr_8d311b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'uploaded_at'], name='documents_d_status_7e2894_idx'),
        ),
    ]
