# Generated by Django 4.2.7 on 2026-04-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('metric_type', models.CharField(choices=[('total_registrations', 'Total Registrations'), ('approved_registrations', 'Approved Registrations'), ('rejected_registrations', 'Rejected Registrations'), ('pending_reviews', 'Pending Manual Reviews'), ('ai_accuracy', 'AI Verification Accuracy'), ('average_processing_time', 'Average Processing Time'), ('state_distribution', 'State-wise Distribution'), ('rejection_reasons', 'Rejection Reasons Breakdown')], max_length=30)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value', models.FloatField(default=0.0)),
                ('value_text', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_frequency_minutes', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Dashboard Metric',
                'verbose_name_plural': 'Dashboard Metrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('daily_registration', 'Daily Registration Report'), ('weekly_registration', 'Weekly Registration Report'), ('monthly_registration', 'Monthly Registration Report'), ('rejection_analysis', 'Rejection Analysis Report'), ('ai_performance', 'AI Performance Report'), ('officer_performance', 'Officer Performance Report'), ('state_lga_summary', 'State/LGA Summary Report'), ('anomaly_report', 'Anomaly Detection Report'), ('custom', 'Custom Report')], max_length=30)),
                ('default_parameters', models.JSONField(default=dict)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('email_recipients', models.JSONField(default=list, help_text='List of email addresses to receive the report')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_run', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('daily_registration', 'Daily Registration Report'), ('weekly_registration', 'Weekly Registration Report'), ('monthly_registration', 'Monthly Registration Report'), ('rejection_analysis', 'Rejection Analysis Report'), ('ai_performance', 'AI Performance Report'), ('officer_performance', 'Officer Performance Report'), ('state_lga_summary', 'State/LGA Summary Report'), ('anomaly_report', 'Anomaly Detection Report'), ('custom', 'Custom Report')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Report generation parameters')),
                ('data', models.JSONField(default=dict, help_text='Generated report data')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/%Y/%m/%d/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/csv/%Y/%m/%d/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/%Y/%m/%d/')),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('generation_time_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'), models.Index(fields=['generated_by', 'created_at'], name='reports_rep_generat_b60f00_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx')],
            },
        ),
    ]
