# Generated by Django 4.2.7 on 2026-04-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_rename_registratio_state_o_e9baab_idx_registratio_state_o_40d8f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_type', models.CharField(choices=[('photo', 'Passport Photo'), ('fingerprint_left_thumb', 'Left Thumb Fingerprint'), ('fingerprint_right_thumb', 'Right Thumb Fingerprint'), ('fingerprint_left_index', 'Left Index Fingerprint'), ('fingerprint_right_index', 'Right Index Fingerprint')], max_length=30)),
                ('image_file', models.ImageField(help_text='Biometric image file', upload_to='biometrics/%Y/%m/%d/')),
                ('quality_score', models.FloatField(default=0.0, help_text='Image quality score (0-1)')),
                ('features_extracted', models.BooleanField(default=False, help_text='Whether biometric features were successfully extracted')),
                ('feature_data', models.JSONField(default=dict, help_text='Extracted biometric features')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_biometrics', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_data', to='registration.voterregistration')),
            ],
            options={
                'verbose_name': 'Biometric Data',
                'verbose_name_plural': 'Biometric Data',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('photo_face_match', 'Photo-Face Match'), ('fingerprint_match', 'Fingerprint Match'), ('photo_fingerprint_consistency', 'Photo-Fingerprint Consistency')], max_length=30)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether verification passed')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Verification confidence score (0-1)')),
                ('verification_details', models.JSONField(default=dict, help_text='Detailed verification results')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_verifications', to='registration.voterregistration')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Verification',
                'verbose_name_plural': 'Biometric Verifications',
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['registration', 'verification_type'], name='biometrics__registr_e7bc84_idx'), models.Index(fields=['is_verified', 'confidence_score'], name='biometrics__is_veri_1dc8f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_data', models.BinaryField(help_text='Serialized biometric template')),
                ('template_type', models.CharField(help_text='Type of template (e.g., fingerprint minutiae, face embedding)', max_length=50)),
                ('algorithm_version', models.CharField(default='1.0', help_text='Algorithm version used to generate template', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('biometric_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='biometrics.biometricdata')),
            ],
            options={
                'verbose_name': 'Biometric Template',
                'verbose_name_plural': 'Biometric Templates',
                'indexes': [models.Index(fields=['template_type', 'algorithm_version'], name='biometrics__templat_00c34c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='biometricdata',
            index=models.Index(fields=['registration', 'biometric_type'], name='biometrics__registr_c6d831_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdata',
            index=models.Index(fields=['quality_score'], name='biometrics__quality_079329_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricdata',
            unique_together={('registration', 'biometric_type')},
        ),
    ]
